# version format
version: "{build}"

# Build worker image (VM template)
image: Visual Studio 2015

# clone directory
clone_folder: c:\projects\automation-for-humans

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - cinst winflexbison make mingw
  - pip install selenium requests pysocks urllib3 --upgrade
  - refreshenv

# to disable automatic builds
build: off

# scripts to run before build
before_test:
  - git submodule update --init --recursive
  - make -d -C dsl win

# to run your custom scripts instead of automatic tests
test_script:
  - python src/automate.py
